[book]
title = "Attacking and Auditing Docker Containers and Kubernetes Clusters"
author = "Appsecco"
description = "Appsecco training course content on Attacking and Auditing Dockers Containers and Kubernetes Clusters"
language = "en"
multilingual = false
src = "src"

[output.html]
google-analytics = "UA-15752161-2"
